server {
    listen 443 ssl;
    server_name arentwe.justlearning.net;

    ssl_certificate     /usr/share/nginx/ssl/chain.pem;
    ssl_certificate_key /usr/share/nginx/ssl/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /index.html {
        try_files $uri =404;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|otf|json)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}
